name: Auto Update Website
on:
    push:
        branches: "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              env : secret: ${{ secret.PAT}}
            - name: Update website
              run: git fetch https://"$secret"@github.com/DerangedLunacy.Me main && git reset --hard FETCH_HEAD