name: Auto Update Website
on:
    push:
        branches: "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Push to private repo to update on server
              run: |
                export GITHUB_TOKEN=${{ secrets.PAT }}
                git clone https://github.com/Slightly-Deranged-Lunatic/DerangedLunacy.Me
                cd DerangedLunacy.Me
                git push https://${{ secrets.PAT }}@github.com/Slightly-Deranged-Lunatic/DerangedLunacy.Me-Runner --force
